spring:
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 5MB

      # 单次请求文件的总大小
      max-request-size: 5MB

  mvc:
    converters:
      preferred-json-mapper: fastjson
    pathmatch:
      matching-strategy: ant_path_matcher

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useSSL=false
    username: root
    password: "root"

server:
  error:
    include-stacktrace: never
    include-message: never
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
